#!/usr/bin/env bash

ffenv_list() {
    default=$(ffenv_get_default)
    current=$FFMPEG_CURRENT
    for f in $(ls $FFMPEG_ROOT)
    do
        if [[ $f == "default" ]]
        then
            :
        else
            if [[ $f == "$current" ]]
            then
                echo -n "* "
            else
                echo -n "  "
            fi
            echo -n $f
            if [[ $f == "$default" ]]
            then
                echo " (default)"
            else
                echo
            fi
        fi
    done
}

ffenv_update_path() {
    new_path=$(echo -n $1 | tr ':' '\n' | egrep -v "^$FFMPEG_ROOT" | tr '\n' ':')
    new_path="$2:$new_path"
    echo "${new_path::-1}"  # Remove trailing colon
}

ffenv_update_path_and_ld_library_path() {
   export PATH=$(ffenv_update_path "$PATH" $FFMPEG_HOME/bin)
   export LD_LIBRARY_PATH=$(ffenv_update_path "$LD_LIBRARY_PATH" $FFMPEG_HOME/lib)
}

ffenv_use() {
    if [[ ! -d "$FFMPEG_ROOT/$1" ]]
    then
        echo "Unknown version: $1" >&2
        echo "Available versions: " >&2
        list >&2
        return 1
    fi
    export FFMPEG_CURRENT=$1
    export FFMPEG_HOME=$FFMPEG_ROOT/$FFMPEG_CURRENT
    ffenv_update_path_and_ld_library_path
}

ffenv_get_name() {
    if [[ -z $2 ]]
    then
        echo "$(echo -n $1 | sed -re 's/^n([0-9.]+)$/\1/g')"
    else
        echo $2
    fi
}

ffenv_setup_repo() {
    version=$1
    name=$(ffenv_get_name $1 $2)
    repo=$FFMPEG_ROOT/$name/gitrepo
    echo "repo: $repo"
    if [[ -e $repo/.git ]]
    then
        echo "Repo allready exists: $repo" >&2
        return 1
    else
        version_dir=$FFMPEG_ROOT/$name
        mkdir -p $version_dir
        (cd $FFMPEG_MAIN_REPO; git worktree add $repo $version)
    fi
}

ffenv_configure_build() {
    name=$1
    repo=$FFMPEG_ROOT/$name/gitrepo
    builddir=$FFMPEG_ROOT/$name/build
    if [[ ! -d $repo ]]
    then
        echo "Repo $repo does not exist"
        return 1
    fi
    mkdir -p $builddir
    cd $builddir
    args="$(cat ~/.ffenv/build-configs/default | tr '\n' ' ') --prefix=$FFMPEG_ROOT/$name"
    $repo/configure $args
}

ffenv_install_version() {
    version=$1
    name=$(ffenv_get_name $1 $2)
    echo "Installing version $version"
    if [[ ! -e $FFMPEG_ROOT/$name/gitrepo/.git ]]
    then
        ffenv_setup_repo $version $name
    fi
    if [[ ! -d $FFMPEG_ROOT/$name/build/ffbuild ]]
    then
        ffenv_configure_build $name
    fi
    cd $FFMPEG_ROOT/$name/build
    make install
}


ffenv_get_default() {
    if [[ -h $FFMPEG_ROOT/default ]]
    then
        basename $(readlink -f $FFMPEG_ROOT/default)
    else
        ls -1 $FFMPEG_ROOT | head -n1
    fi
}

ffenv_init() {
    if [[ -z "$FFMPEG_MAIN_REPO" ]]
    then
        export FFMPEG_MAIN_REPO=$HOME/gitrepos/thirdparty/FFmpeg
    fi
    if [[ -z "$FFMPEG_ROOT" ]]
    then
        export FFMPEG_ROOT=$HOME/ffmpeg
    fi

    if [[ -z "$FFMPEG_CURRENT" ]]
    then
        export FFMPEG_CURRENT=$(ffenv_get_default)
    fi
    export FFMPEG_HOME=$FFMPEG_ROOT/$FFMPEG_CURRENT
    ffenv_update_path_and_ld_library_path
}

ffenv() {
    if [[ $1 == "list" ]]
    then
        ffenv_list
    elif [[ $1 == "use" ]]
    then
        ffenv_use $2
    fi
}

ffenv_init

